### ISSUE TITLE
ValueError: MODE_OPENPGP requires an IV

### ISSUE THREAD

**Issue by drumer2142** [drumer2142/CBI-CSE-MSc#2]
Traceback (most recent call last):
  File "index.py", line 53, in <module>
    main()
  File "index.py", line 50, in main
    new_enc = Encrypt(hashed_pwd)
  File "index.py", line 18, in __init__
    self.encrypt_zip()
  File "index.py", line 40, in encrypt_zip
    cipher_aes = AES.new(session_key, AES.MODE_OPENPGP)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/AES.py", line 94, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/blockalgo.py", line 155, in __init__
    raise ValueError("MODE_OPENPGP requires an IV")
ValueError: MODE_OPENPGP requires an IV

**Comment by drumer2142** [comment]
Used MODE_CBC
