### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by drumer2142** [drumer2142/CBI-CSE-MSc#4]
# Need to create a pad_txt function
➜  CBI-CSE-MSc git:(develop) ✗ sudo python3 index.py
Please insert a password: PAS
Len session key:  16
Traceback (most recent call last):
  File "index.py", line 65, in <module>
    main()
  File "index.py", line 58, in main
    new_enc = Encrypt(hashed_pwd)
  File "index.py", line 19, in __init__
    self.encrypt_zip()
  File "index.py", line 50, in encrypt_zip
    ciphertext, tag = cipher_aes.encrypt(cfg.tests['data'].encode())
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/blockalgo.py", line 244, in encrypt
    return self._cipher.encrypt(plaintext)
ValueError: Input strings must be a multiple of 16 in length

**Comment by drumer2142** [comment]
def pad_txt(self, txt_str):
        while len(txt_str) % 8 != 0:
            txt_str += ' '
        return txt_str
